### ISSUE TITLE
USER STORY: Deploy Backend

### ISSUE THREAD

**Issue by ibrahimjasim** [ibrahimjasim/SnapGram-API#4]
As a developer, I want to deploy the backend to Heroku, So that it is accessible and functional on the web.

### Acceptance Criteria
---
* #### API Functionality:

  - The Django REST Framework is correctly installed and configured on Heroku.
  
   - The API functions with the expected behavior as observed in the local development environment.
   
* #### Accessibility:

  -  The application is accessible via the Heroku URL.
  
  - The API routes and endpoints are accessible and respond appropriately.
### Tasks
- [x] Create ElephantSQL database
- [x] Create Heroku APP, add applicable config-vars
- [x] Deploy App
- [x] Check URLs work as expected
- [x] Install and configure Django REST Framework
- [x] Update and synchronize database models
- [x] Test API functionality locally
- [x] Deploy the backend with Django REST Framework to Heroku
- [x] Verify API functionality on the Heroku-deployed application
